# Render deployment configuration for Constellation
# https://render.com/docs/yaml-spec

services:
  # FastAPI Web Service
  - type: web
    name: constellation-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: cd apps/api && uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: constellation-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11"
      - key: HOST
        value: "0.0.0.0"
    healthCheckPath: /health

databases:
  # PostgreSQL Database
  - name: constellation-db
    databaseName: planet
    user: constellation
    plan: free
    region: oregon
    ipAllowList: []
