services:
  # Development Postgres - shared across all repos (api, worker, etc)
  postgres:
    image: postgres:18
    container_name: planet-dev-postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=planet
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d planet']
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - planet_pgdata:/var/lib/postgresql/data
    networks:
      - planet-dev

  # NATS message broker
  nats:
    image: nats:2
    container_name: planet-dev-nats
    ports:
      - '4222:4222'
      - '8222:8222'
    networks:
      - planet-dev

volumes:
  planet_pgdata:

networks:
  planet-dev:
    name: planet-dev
    driver: bridge
