version: "3.9"
services:
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=planet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  nats:
    image: nats:2
    ports:
      - "4222:4222"
      - "8222:8222"
volumes:
  pgdata:
