openapi: 3.1.0
info:
  title: Constellation API
  description: GPU task orchestrator with real-time insights
  version: 0.1.0

paths:
  /:
    get:
      summary: Root
      description: Root endpoint - API info
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}

  /health:
    get:
      summary: Health
      description: Health check endpoint
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}

  /jobs:
    get:
      summary: List Jobs
      description: Get all jobs from the database
      operationId: list_jobs_jobs_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobResponse'
    post:
      summary: Create Job
      description: Create a new job
      operationId: create_job_jobs_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobCreate'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'

  /jobs/{job_id}:
    get:
      summary: Get Job
      description: Get a single job by ID
      operationId: get_job_jobs__job_id__get
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'

components:
  schemas:
    JobCreate:
      type: object
      required: [name]
      properties:
        name:
          type: string
          minLength: 1
          description: Job name
        params:
          type: object
          additionalProperties: true
          description: Job parameters as JSON
          default: {}
        priority:
          type: integer
          description: Job priority (higher = more important)
          default: 0
        submitted_by:
          anyOf:
            - type: string
            - type: 'null'
          description: Who submitted the job

    JobResponse:
      type: object
      required: [id, name, params, priority, state, created_at, submitted_by]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        params:
          type: object
          additionalProperties: true
        priority:
          type: integer
        state:
          type: string
        created_at:
          type: string
          format: date-time
        submitted_by:
          anyOf:
            - type: string
            - type: 'null'

    HTTPValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'

    ValidationError:
      type: object
      required: [loc, msg, type]
      properties:
        loc:
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
        type:
          type: string
