---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    name: infrastructure

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: infrastructure
data:
  nats.conf: |
    # NATS Server Configuration
    port: 4222
    http_port: 8222

    # JetStream Configuration
    jetstream {
      store_dir: /data/jetstream
      max_memory_store: 2Gi
      max_file_store: 10Gi
    }

    # Limits
    max_payload: 8MB
    max_pending: 256MB

    # Logging
    debug: false
    trace: false
    logtime: true

---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: infrastructure
  labels:
    app: nats
spec:
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
      protocol: TCP
    - name: monitor
      port: 8222
      targetPort: 8222
      protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: infrastructure
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
        app.kubernetes.io/name: nats
        app.kubernetes.io/component: messaging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7777"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: nats
        image: nats:2.10
        ports:
        - name: client
          containerPort: 4222
        - name: monitor
          containerPort: 8222
        command:
          - "nats-server"
          - "--config"
          - "/etc/nats-config/nats.conf"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats-config
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8222
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8222
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: nats-config
      - name: data
        emptyDir: {}
