services:
  test-db:
    image: postgres:16-alpine
    container_name: constellation-test-db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - test_db_data:/var/lib/postgresql/data

volumes:
  test_db_data:
