name: Deploy Web

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - '.github/workflows/deploy-web.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - '.github/workflows/deploy-web.yml'
  workflow_run:
    workflows: ["Deploy API"]
    types:
      - completed

env:
  PROJECT_ID: overflying-cluster
  REGION: europe-west1

jobs:
  test-web:
    name: Test Web
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'workflow_run' || 
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get staging API URL from Secret Manager
        id: api-url
        run: |
          API_URL=$(gcloud secrets versions access latest --secret="api-url-staging" --project=${{ env.PROJECT_ID }})
          echo "url=$API_URL" >> $GITHUB_OUTPUT

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: apps/web
        run: bun install --frozen-lockfile

      - name: Run unit tests
        working-directory: apps/web
        env:
          NEXT_PUBLIC_API_URL: ${{ steps.api-url.outputs.url }}
        run: bun run test:coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        if: always()
        with:
          files: ./apps/web/coverage/coverage-final.json
          flags: web
          name: web-coverage
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Test Success
        if: success()
        run: |
          echo "========================================="
          echo "   WEB TESTS PASSED SUCCESSFULLY!"
          echo "========================================="

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test-web
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: web-staging
      url: https://staging.overfly.ing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get staging API URL from Secret Manager
        id: secrets
        run: |
          API_URL=$(gcloud secrets versions access latest --secret="api-url-staging" --project=${{ env.PROJECT_ID }})
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: apps/web
        run: bun install --frozen-lockfile

      - name: Build static export
        working-directory: apps/web
        env:
          NEXT_PUBLIC_API_URL: ${{ steps.secrets.outputs.api_url }}
        run: bun run build

      - name: Deploy to Firebase Hosting (Staging)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.GCP_SA_KEY }}'
          channelId: live
          projectId: overflying-web
          target: overflying-staging
          entryPoint: apps/web

      - name: Staging Deployment Success
        run: |
          echo "========================================="
          echo "   STAGING DEPLOYED!"
          echo "========================================="
          echo "URL: https://staging.overfly.ing"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: web-production
      url: https://overfly.ing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get production API URL from Secret Manager
        id: secrets
        run: |
          API_URL=$(gcloud secrets versions access latest --secret="api-url-production" --project=${{ env.PROJECT_ID }})
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: apps/web
        run: bun install --frozen-lockfile

      - name: Build static export
        working-directory: apps/web
        env:
          NEXT_PUBLIC_API_URL: ${{ steps.secrets.outputs.api_url }}
        run: bun run build

      - name: Deploy to Firebase Hosting (Production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.GCP_SA_KEY }}'
          channelId: live
          projectId: overflying-web
          target: overflying-production
          entryPoint: apps/web

      - name: Production Deployment Success
        run: |
          echo "========================================="
          echo "   PRODUCTION DEPLOYED!"
          echo "========================================="
          echo "URL: https://overfly.ing"