name: Deploy Web

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy-web.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy-web.yml"
  workflow_run:
    workflows: ["Deploy API"]
    types:
      - completed
  workflow_dispatch: # Add this to enable manual triggers

env:
  PROJECT_ID: overflying-web
  REGION: europe-west1

jobs:
  test-web:
    name: Test Web
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_WEB }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get staging API URL from Secret Manager
        id: api-url
        run: |
          API_URL=$(gcloud secrets versions access latest --secret="api-url-staging" --project=${{ env.PROJECT_ID }})
          echo "url=$API_URL" >> $GITHUB_OUTPUT

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: apps/web
        run: bun install --frozen-lockfile

      - name: Run unit tests
        working-directory: apps/web
        env:
          NEXT_PUBLIC_API_URL: ${{ steps.api-url.outputs.url }}
        run: |
          bun install --frozen-lockfile
          npm install @rollup/rollup-linux-x64-gnu @esbuild/linux-x64 --no-save
          bun run test:coverage

      - name: List coverage files
        if: always()
        run: |
          echo "=== Coverage directory contents ==="
          ls -la apps/web/coverage/ || echo "Coverage directory not found"
          find apps/web/coverage -type f || echo "No coverage files found"

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        if: always()
        with:
          directory: ./apps/web/coverage
          flags: web
          name: web-coverage
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Test Success
        if: success()
        run: |
          echo "========================================="
          echo "   WEB TESTS PASSED SUCCESSFULLY!"
          echo "========================================="

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test-web
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: web-staging
      url: https://staging.overfly.ing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_WEB }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase App Hosting (Staging)
        working-directory: apps/web
        run: |
          firebase apphosting:rollouts:create staging-overflying \
            --project ${{ env.PROJECT_ID }} \
            --config apphosting.staging.yaml \
            --token "$ACCESS_TOKEN"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY_WEB }}

      - name: Staging Deployment Success
        run: |
          echo "========================================="
          echo "   STAGING DEPLOYED TO APP HOSTING!"
          echo "========================================="
          echo "URL: https://staging.overfly.ing"
          echo "Backend: staging-overflying"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: web-production
      url: https://overfly.ing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_WEB }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase App Hosting (Production)
        working-directory: apps/web
        run: |
          firebase apphosting:rollouts:create production-overflying \
            --project ${{ env.PROJECT_ID }} \
            --config apphosting.production.yaml \
            --token "$ACCESS_TOKEN"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY_WEB }}

      - name: Production Deployment Success
        run: |
          echo "========================================="
          echo "   PRODUCTION DEPLOYED TO APP HOSTING!"
          echo "========================================="
          echo "URL: https://overfly.ing"
          echo "Backend: production-overflying"
