name: Deploy API

on:
  push:
    branches: [main]
    paths:
      - "apps/api/**"
      - "k8s/api/**"
      - ".github/workflows/deploy-api.yml"
      - ".github/workflows/reusable-*.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/api/**"
      - "k8s/api/**"
      - ".github/workflows/deploy-api.yml"

env:
  PROJECT_ID: overflying-cluster
  REGION: europe-west1
  GKE_CLUSTER: overflying-autopilot
  REGISTRY: europe-west1-docker.pkg.dev
  REPOSITORY: overflying-images
  IMAGE_NAME: api

jobs:
  test-api:
    name: Test API
    uses: ./.github/workflows/reusable-test-python.yml
    with:
      app_path: apps/api
      python_version: "3.11"
      coverage_flags: api
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-and-push:
    name: Build and Push API Image
    needs: test-api
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable-build-push-python.yml
    with:
      app_path: apps/api
      image_name: api
      project_id: overflying-cluster
      region: europe-west1
      registry: europe-west1-docker.pkg.dev
      repository: overflying-images
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  deploy-staging:
    name: Deploy to Staging
    needs: build-and-push
    uses: ./.github/workflows/reusable-deploy-gke.yml
    with:
      environment_name: api-staging
      environment_url: https://staging.api.overfly.ing
      deployment_name: api-staging
      namespace: staging
      container_name: api
      image_tag: ${{ needs.build-and-push.outputs.image_tag }}
      project_id: overflying-cluster
      region: europe-west1
      cluster: overflying-autopilot
      service_name: api-service
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  deploy-production:
    name: Deploy to Production
    needs: deploy-staging
    uses: ./.github/workflows/reusable-deploy-gke.yml
    with:
      environment_name: api-production
      environment_url: https://api.overfly.ing
      deployment_name: api-production
      namespace: production
      container_name: api
      image_tag: ${{ needs.build-and-push.outputs.image_tag }}
      project_id: overflying-cluster
      region: europe-west1
      cluster: overflying-autopilot
      service_name: api-service
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
